#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# Script: 03_kraken2_classification.sh
# Author: Zhaoxia Wang
# Version: v1.0
# Date: 2024-10-05
#
# Purpose:
#   Run Kraken2 on non-host cfRNA reads under two host-filtering modes:
#     - strict  : paired-unmapped (both mates unmapped)
#     - relaxed : any-unmapped    (at least one mate unmapped)
#
#   The script supports both CAD and TB cohorts and assumes that
#   non-host FASTQ files were generated by the previous host-mapping step:
#
#     strict mode  FASTQ:
#       ${PROJECT_ROOT}/nonhost/<COHORT>/strict_paired_unmapped/SAMPLE.strict_R1.fastq.gz
#       ${PROJECT_ROOT}/nonhost/<COHORT>/strict_paired_unmapped/SAMPLE.strict_R2.fastq.gz
#
#     relaxed mode FASTQ:
#       ${PROJECT_ROOT}/nonhost/<COHORT>/relaxed_any_unmapped/SAMPLE.relaxed_R1.fastq.gz
#       ${PROJECT_ROOT}/nonhost/<COHORT>/relaxed_any_unmapped/SAMPLE.relaxed_R2.fastq.gz
#
# Usage examples:
#   bash 03_kraken2_classification.sh CAD strict
#   bash 03_kraken2_classification.sh TB relaxed
#   bash 03_kraken2_classification.sh CAD both
#
# Required edits before running:
#   1) Set PROJECT_ROOT to your project directory.
#   2) Set KRAKEN2_DB to the path of your Kraken2 database
#      (e.g. k2_standard_08gb_20240605).
###############################################################################

# ------------------------- USER CONFIGURATION -------------------------------#

# Root directory of the project (edit this to your own path)
PROJECT_ROOT="/path/to/project_root"

# Kraken2 database (edit this to your own path)
KRAKEN2_DB="/path/to/kraken2_db/k2_standard_08gb_20240605"

# Number of threads for Kraken2
THREADS=8

# ------------------------- INPUT ARGUMENTS ---------------------------------#

if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <COHORT> <MODE>"
  echo "  COHORT: CAD or TB"
  echo "  MODE  : strict | relaxed | both"
  exit 1
fi

COHORT="$1"
MODE="$2"

case "${COHORT}" in
  CAD|cad) COHORT="CAD" ;;
  TB|tb)   COHORT="TB" ;;
  *)
    echo "Error: COHORT must be CAD or TB"
    exit 1
    ;;
esac

case "${MODE}" in
  strict|relaxed|both)
    ;;
  *)
    echo "Error: MODE must be strict, relaxed, or both"
    exit 1
    ;;
esac

echo ">>> Running Kraken2 for cohort: ${COHORT}, mode: ${MODE}"

# ------------------------- DIRECTORY LAYOUT --------------------------------#

NONHOST_BASE="${PROJECT_ROOT}/nonhost/${COHORT}"

STRICT_FASTQ_DIR="${NONHOST_BASE}/strict_paired_unmapped"
RELAX_FASTQ_DIR="${NONHOST_BASE}/relaxed_any_unmapped"

KRAKEN_BASE="${PROJECT_ROOT}/kraken2/${COHORT}"
LOG_DIR="${PROJECT_ROOT}/logs/kraken2_${COHORT}"

mkdir -p "${KRAKEN_BASE}" "${LOG_DIR}"

# ------------------------- FUNCTIONS ---------------------------------------#

run_kraken_mode () {
  local mode="$1"        # "strict" or "relaxed"
  local fastq_dir="$2"   # input FASTQ directory

  local out_dir="${KRAKEN_BASE}/${mode}"
  local rep_dir="${out_dir}/reports"
  local raw_dir="${out_dir}/outputs"

  mkdir -p "${out_dir}" "${rep_dir}" "${raw_dir}"

  echo ">>> Processing mode: ${mode}"
  echo "    FASTQ directory : ${fastq_dir}"
  echo "    Output directory: ${out_dir}"

  local pattern=""
  local suffix_R1=""
  local suffix_R2=""

  if [[ "${mode}" == "strict" ]]; then
    pattern="*.strict_R1.fastq.gz"
    suffix_R1=".strict_R1.fastq.gz"
    suffix_R2=".strict_R2.fastq.gz"
  else
    pattern="*.relaxed_R1.fastq.gz"
    suffix_R1=".relaxed_R1.fastq.gz"
    suffix_R2=".relaxed_R2.fastq.gz"
  fi

  for fq1 in "${fastq_dir}"/${pattern}; do
    if [[ ! -e "${fq1}" ]]; then
      echo "No FASTQ files found for mode ${mode} in ${fastq_dir}"
      return
    fi

    sample=$(basename "${fq1}" "${suffix_R1}")
    fq2="${fastq_dir}/${sample}${suffix_R2}"

    if [[ ! -f "${fq2}" ]]; then
      echo "Warning: missing R2 file for sample ${sample} in mode ${mode}, skipping."
      continue
    fi

    echo "-----------------------------------------------------------------"
    echo ">>> [${mode}] Running Kraken2 for sample: ${sample}"
    echo "-----------------------------------------------------------------"

    out_file="${raw_dir}/${sample}.${mode}.kraken2.out"
    rep_file="${rep_dir}/${sample}.${mode}.kraken2.report"
    log_file="${LOG_DIR}/${sample}.${mode}.kraken2.log"

    if [[ -f "${rep_file}" ]]; then
      echo ">>> [${sample}] Kraken2 report already exists, skipping."
      continue
    fi

    kraken2 \
      --db "${KRAKEN2_DB}" \
      --paired \
      --gzip-compressed \
      --threads "${THREADS}" \
      --use-names \
      --output "${out_file}" \
      --report "${rep_file}" \
      "${fq1}" "${fq2}" \
      > "${log_file}" 2>&1

    echo ">>> [${sample}] Kraken2 finished for mode ${mode}"
  done
}

# ------------------------- MAIN CONTROL FLOW -------------------------------#

if [[ "${MODE}" == "strict" || "${MODE}" == "both" ]]; then
  run_kraken_mode "strict"  "${STRICT_FASTQ_DIR}"
fi

if [[ "${MODE}" == "relaxed" || "${MODE}" == "both" ]]; then
  run_kraken_mode "relaxed" "${RELAX_FASTQ_DIR}"
fi

echo ">>> Kraken2 classification finished for cohort ${COHORT}, mode ${MODE}"
