#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# Script: 04_metaphlan_profiling.sh
# Author: Zhaoxia Wang
# Version: v1.0
# Date: 2024-10-07
#
# Purpose:
#   Run MetaPhlAn 4 on non-host cfRNA reads under two host-filtering modes:
#     - strict  : paired-unmapped (both mates unmapped)
#     - relaxed : any-unmapped    (at least one mate unmapped)
#
#   The script supports both CAD and TB cohorts and assumes that
#   non-host FASTQ files were generated by the previous host-mapping step:
#
#     strict mode  FASTQ:
#       ${PROJECT_ROOT}/nonhost/<COHORT>/strict_paired_unmapped/SAMPLE.strict_R1.fastq.gz
#       ${PROJECT_ROOT}/nonhost/<COHORT>/strict_paired_unmapped/SAMPLE.strict_R2.fastq.gz
#
#     relaxed mode FASTQ:
#       ${PROJECT_ROOT}/nonhost/<COHORT>/relaxed_any_unmapped/SAMPLE.relaxed_R1.fastq.gz
#       ${PROJECT_ROOT}/nonhost/<COHORT>/relaxed_any_unmapped/SAMPLE.relaxed_R2.fastq.gz
#
# Usage examples:
#   bash 04_metaphlan_profiling.sh CAD strict
#   bash 04_metaphlan_profiling.sh TB relaxed
#   bash 04_metaphlan_profiling.sh CAD both
#
# Required edits before running:
#   1) Set PROJECT_ROOT to your project directory.
#   2) Set MPA_DB_DIR to the path of your MetaPhlAn database directory.
#   3) Set MPA_INDEX to the index name (e.g. mpa_vJan25_CHOCOPhlAnSGB_202503).
###############################################################################

# ------------------------- USER CONFIGURATION -------------------------------#

# Root directory of the project (edit this to your own path)
PROJECT_ROOT="/path/to/project_root"

# MetaPhlAn Bowtie2 database directory (edit this to your own path)
MPA_DB_DIR="/path/to/metaphlan_db"

# MetaPhlAn index name (ChocoPhlAn SGB database)
MPA_INDEX="mpa_vJan25_CHOCOPhlAnSGB_202503"

# Number of threads for MetaPhlAn
THREADS=8

# ------------------------- INPUT ARGUMENTS ---------------------------------#

if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <COHORT> <MODE>"
  echo "  COHORT: CAD or TB"
  echo "  MODE  : strict | relaxed | both"
  exit 1
fi

COHORT="$1"
MODE="$2"

case "${COHORT}" in
  CAD|cad) COHORT="CAD" ;;
  TB|tb)   COHORT="TB" ;;
  *)
    echo "Error: COHORT must be CAD or TB"
    exit 1
    ;;
esac

case "${MODE}" in
  strict|relaxed|both)
    ;;
  *)
    echo "Error: MODE must be strict, relaxed, or both"
    exit 1
    ;;
esac

echo ">>> Running MetaPhlAn for cohort: ${COHORT}, mode: ${MODE}"

# ------------------------- DIRECTORY LAYOUT --------------------------------#

NONHOST_BASE="${PROJECT_ROOT}/nonhost/${COHORT}"

STRICT_FASTQ_DIR="${NONHOST_BASE}/strict_paired_unmapped"
RELAX_FASTQ_DIR="${NONHOST_BASE}/relaxed_any_unmapped"

MPA_BASE="${PROJECT_ROOT}/metaphlan/${COHORT}"
LOG_DIR="${PROJECT_ROOT}/logs/metaphlan_${COHORT}"

mkdir -p "${MPA_BASE}" "${LOG_DIR}"

# ------------------------- FUNCTIONS ---------------------------------------#

run_metaphlan_mode () {
  local mode="$1"        # "strict" or "relaxed"
  local fastq_dir="$2"   # input FASTQ directory

  local out_dir="${MPA_BASE}/${mode}"
  local prof_dir="${out_dir}/profiles"
  local bt2_dir="${out_dir}/bowtie2out"

  mkdir -p "${out_dir}" "${prof_dir}" "${bt2_dir}"

  echo ">>> Processing MetaPhlAn mode: ${mode}"
  echo "    FASTQ directory : ${fastq_dir}"
  echo "    Output directory: ${out_dir}"

  local pattern=""
  local suffix_R1=""
  local suffix_R2=""

  if [[ "${mode}" == "strict" ]]; then
    pattern="*.strict_R1.fastq.gz"
    suffix_R1=".strict_R1.fastq.gz"
    suffix_R2=".strict_R2.fastq.gz"
  else
    pattern="*.relaxed_R1.fastq.gz"
    suffix_R1=".relaxed_R1.fastq.gz"
    suffix_R2=".relaxed_R2.fastq.gz"
  fi

  for fq1 in "${fastq_dir}"/${pattern}; do
    if [[ ! -e "${fq1}" ]]; then
      echo "No FASTQ files found for mode ${mode} in ${fastq_dir}"
      return
    fi

    local sample
    sample=$(basename "${fq1}" "${suffix_R1}")
    local fq2="${fastq_dir}/${sample}${suffix_R2}"

    if [[ ! -f "${fq2}" ]]; then
      echo "Warning: missing R2 file for sample ${sample} in mode ${mode}, skipping."
      continue
    fi

    echo "-----------------------------------------------------------------"
    echo ">>> [${mode}] Running MetaPhlAn for sample: ${sample}"
    echo "-----------------------------------------------------------------"

    local prof_file="${prof_dir}/${sample}.${mode}.metaphlan_profile.txt"
    local bt2_file="${bt2_dir}/${sample}.${mode}.bowtie2.bz2"
    local log_file="${LOG_DIR}/${sample}.${mode}.metaphlan.log"

    if [[ -f "${prof_file}" ]]; then
      echo ">>> [${sample}] MetaPhlAn profile already exists, skipping."
      continue
    fi

    # MetaPhlAn expects paired-end reads as a comma-separated list
    local input_pe="${fq1},${fq2}"

    metaphlan \
      "${input_pe}" \
      --input_type fastq \
      --bowtie2db "${MPA_DB_DIR}" \
      --index "${MPA_INDEX}" \
      --bowtie2out "${bt2_file}" \
      --nproc "${THREADS}" \
      -o "${prof_file}" \
      > "${log_file}" 2>&1

    echo ">>> [${sample}] MetaPhlAn finished for mode ${mode}"
  done
}

# ------------------------- MAIN CONTROL FLOW -------------------------------#

if [[ "${MODE}" == "strict" || "${MODE}" == "both" ]]; then
  run_metaphlan_mode "strict"  "${STRICT_FASTQ_DIR}"
fi

if [[ "${MODE}" == "relaxed" || "${MODE}" == "both" ]]; then
  run_metaphlan_mode "relaxed" "${RELAX_FASTQ_DIR}"
fi

echo ">>> MetaPhlAn profiling finished for cohort ${COHORT}, mode ${MODE}"
